### ISSUE TITLE
private.4 for xDoctor update/running

### ISSUE THREAD

**Issue by ikemen18** [anarchy9388/toroi#14]
There is an issue where xDoctor sometimes won't update as well as sometimes won't run post upgrade due to the private.4 not being accessible. These are the lines that need adjusting (definition for master_ip). Tried to use cluster_master but the formatting is different than standard IP. 

```
def upgrade_xdoctor(self):
        upgrade_xdoctor = False
        self.msg_output('Checking xDoctor version and upgrading if version is not {}..'.format(self.latest_xdoctor))
        self.msg_output('{}{}{}'.format(self.colors.BLUE, ('-' * 100), self.colors.ENDC))
        for nodeKey, node in self.vdcs['self'].nodes.iteritems():
            if node.versions.xdoctor != self.latest_xdoctor:
                upgrade_xdoctor = True
        if DEBUG:
            upgrade_xdoctor = True
        if upgrade_xdoctor:
            for nodeKey, node in self.vdcs['self'].nodes.iteritems():
                if node.rackrole == 'master':
                    master_ip = node.interfaces['private.4']


 def run_xdoctor(self):
        self.msg_output('Running xDoctor on master node(s):')
        self.msg_output('{}{}{}'.format(self.colors.BLUE, ('-' * 100), self.colors.ENDC))
        for nodeKey, node in self.vdcs['self'].nodes.iteritems():
            if node.rackrole == 'master':
                master_ip = node.interfaces['private.4']

```

**Comment by anarchy9388** [comment]
@ikemen18 

Should be able to do something like this:
```
    def upgrade_xdoctor(self):
        self.msg_output('Checking xDoctor version and upgrading if version is not {}..'.format(self.latest_xdoctor))
        self.msg_output('{}{}{}'.format(self.colors.BLUE, ('-' * 100), self.colors.ENDC))
        for nodeKey, node in self.vdcs['self'].nodes.iteritems():
            if node.versions.xdoctor != self.latest_xdoctor:
                if node.rackrole == 'master':
                    short_name = node.shortname
                    self.msg_output('Upgrading xDoctor on {}'.format(short_name), indent=1)
                    self.copy_to_nodes(file_name=self.xdoctor_path,
                                       targetdir='/home/admin',
                                       MACHINES=short_name)
                    cmd = 'sudo xdoctor -uL /home/admin/{} --reinstall'.format(self.xdoctor_path.split('/')[-1])
                    result = self.run_cmd(cmd, MACHINES=short_name)
                    output = self.ansi_escape.sub('', result[short_name]['stderr'].strip())
                    if 'xDoctor successfully updated' in str(output):
                        self.msg_output('xDoctor successfully updated.', indent=1)
                    else:
                        self.msg_output('Failed to update xDoctor:', indent=1, error=True)
                        self.msg_output('{}'.format(result))
                        exit(666)
        else:
            self.msg_output('xDoctor is up to date.', indent=1)
        self.msg_output()
```

**Comment by ikemen18** [comment]
@anarchy9388 

Initial try: 

```
 Upgrading xDoctor on r1n1
Traceback (most recent call last):
  File "toroi.py", line 607, in <module>
    toroi_inst.main()
  File "toroi.py", line 569, in main
    self.do_pre_check()
  File "toroi.py", line 498, in do_pre_check
    self.upgrade_xdoctor()
  File "toroi.py", line 86, in upgrade_xdoctor
    result = self.run_cmd(cmd, MACHINES=short_name)
  File "/home/admin/toroi-1.7/libs/svc_base.py", line 6150, in run_cmd
    raise (RuntimeError("Names need to be resolved by vdcObj.run_cmd().  Was passed {}".format(MACHINE)))
RuntimeError: Names need to be resolved by vdcObj.run_cmd().  Was passed r1n1
```

**Comment by ikemen18** [comment]
@anarchy9388 

This appears to work, however, it then breaks the output line:

```
                     result = vdcObj.run_cmd('sudo xdoctor -uL /home/admin/{} --reinstall'.format(self.xdoctor_path.split('/')[-1], MACHINES=short_name)
                    output = self.ansi_escape.sub('', result[short_name]['stderr'].strip())
                    if 'xDoctor successfully updated' in str(output):
                        self.msg_output('xDoctor successfully updated.', indent=1)

File "toroi.py", line 87
    output = self.ansi_escape.sub('', result[short_name]['stderr'].strip())
         ^
SyntaxError: invalid syntax
```
